# TODO
# - after success and similar => dashboard
language: python
python:
  - "2.7"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
before_script:
  - "mysql -e 'create database domogik;'"
install:
  - apt-cache search libzmq
  - apt-get install libzmq-dev
  - sudo pip install pyzmq
  - sudo apt-get install python-argparse
  - sudo apt-get install python2.7-dev gcc
  - sudo apt-get install libssl-dev
  - sudo apt-get install libmysqlclient-dev mysql-client
  - sudo apt-get install python-psycopg2
script:
  - cd ~
  - git clone https://github.com/domogik/domogik.git
  - cd domogik
  - git checkout 0.4-candidate
  - sudo python install.py --user $LOGNAME --command-line --domogik_log_level debug --domogik_bind_interface 127.0.0.1 --database_name domogik --database_user travis--rest_interfaces lo --rest_clean_json True --mq_ip 127.0.0.1 --hub_interfaces lo --hub_log_level info --hub_log_bandwidth True --hub_log_invalid_data True
  - sudo /etc/init.d/domogik start
  - cd $TRAVIS_BUILD_DIR
  - python tests/001_configure.py
