# TODO
# - after success and similar => dashboard
addons:
  hosts:
    - domogikhost
python:
  - "2.7"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
before_script:
  - "mysql -e 'create database domogik;'"
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('domopass') WHERE user='travis';\nFLUSH PRIVILEGES;\n" | mysql -u root
install:
  - apt-cache search libzmq
  - sudo apt-get install libzmq3-dev
  - sudo pip install pyzmq
  - sudo apt-get install python-argparse
  - sudo apt-get install python2.7-dev gcc
  - sudo apt-get install libssl-dev
  - sudo apt-get install libmysqlclient-dev mysql-client
  - sudo apt-get install python-psycopg2
script:
  - cd ~
  - git clone https://github.com/domogik/domogik.git
  - cd domogik
  - git checkout 0.4-candidate
  - sudo mkdir -p /var/lock/domogik 
  - sudo chown $LOGNAME:root /var/lock/domogik
  - sudo touch /var/lock/domogik/config.lock 
  - sudo chown $LOGNAME:root /var/lock/domogik/config.lock
  - sudo python install.py --user $LOGNAME --command-line --domogik_log_level debug --domogik_bind_interface 127.0.0.1 --database_name domogik --database_user travis --rest_interfaces lo --rest_clean_json True --mq_ip 127.0.0.1 --hub_interfaces lo --hub_log_level info --hub_log_bandwidth True --hub_log_invalid_data True
  - sudo chown $LOGNAME:root /var/lock/domogik
  - sudo chown $LOGNAME:root /var/lock/domogik/config.lock
  - sudo chown $LOGNAME:root /var/log/domogik/*
  - ls -l /var/lock/domogik/
  - cd $TRAVIS_BUILD_DIR
  - ls -l
  - pwd
  - ln -s $(pwd) /var/lib/domogik/domogik_packages/plugin_diskfree
  - ls -l /var/lib/domogik/plugin_diskfree
  - sudo /etc/init.d/domogik start
  - sleep 180
  - cat /var/log/domogik/manager.log
  - python tests/010_tests.py
after_failure: 
  - ps -ef | grep dmg
  - cat /etc/default/domogik
  - cat /var/log/domogik/diskfree.log
  - cat /var/log/domogik/db_api.log
  - cat /var/log/domogik/dbmgr.log
  - cat /var/log/domogik/manager.log
  - cat /var/log/domogik/rest.log
  - cat /var/log/domogik/xplgw.log
  - cat /var/log/domogik/mq_broker.log
