# TODO
# - unit test : renvoyer un code retour du py != 0 si on a un échec
# - after success and similar => dashboard : http://about.travis-ci.org/fr/docs/user/status-images/
#                                            http://about.travis-ci.org/docs/user/ci-environment/
# - notifications (irc notamment) : http://about.travis-ci.org/fr/docs/user/build-configuration/
#    notifications:
#       on_success: never
#       on_failure: always
# - optimisation : utiliser un .sh dans le repo (plus facilement adaptable). Utiliser le shebang bash + -e : cf https://groups.google.com/forum/#!topic/travis-ci/JtC4WiCMA0w
# - comment gerer les branches ? un yaml dans master suffit ? tester sur depot dmg
python:
  - "2.7"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
env:
  DMG_BRANCH=0.4-candidate
  DMG_PLUGIN=diskfree
install:
  - cd ~
  - git clone https://github.com/domogik/domogik.git
  - cd domogik
  - git checkout $DMG_BRANCH
  - ~/domogik/src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
  - ~/domogik/src/domogik/tests/travis/travis-setup-database.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-domogik.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-plugin.sh 
  - ~/domogik/src/domogik/tests/travis/travis-start-domogik.sh
script:
  - cd $TRAVIS_BUILD_DIR
  - python tests/010_tests.py
after_failure: 
  - ~/domogik/src/domogik/tests/travis/travis-after-failure.sh
notifications:
  irc: "irc.freenode.net#domogik"

