# TODO
# - unit test : renvoyer un code retour du py != 0 si on a un échec
# - after success and similar => dashboard : http://about.travis-ci.org/fr/docs/user/status-images/
#                                            http://about.travis-ci.org/docs/user/ci-environment/
# - notifications (irc notamment) : http://about.travis-ci.org/fr/docs/user/build-configuration/
#    notifications:
#       on_success: never
#       on_failure: always
# - optimisation : utiliser un .sh dans le repo (plus facilement adaptable). Utiliser le shebang bash + -e : cf https://groups.google.com/forum/#!topic/travis-ci/JtC4WiCMA0w
# - comment gerer les branches ? un yaml dans master suffit ? tester sur depot dmg
addons:
  hosts:
    - domogikhost
python:
  - "2.7"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
env:
  DMG_BRANCH=0.4-candidate
install:
  - cd ~
  - git clone https://github.com/domogik/domogik.git
  - cd domogik
  - git checkout $DMG_BRANCH
  - src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
  - src/domogik/tests/travis/travis-setup-database.sh
  - src/domogik/tests/travis/travis-install-domogik.sh
  - cd $TRAVIS_BUILD_DIR
  - ls -l
  - pwd
  - ln -s $(pwd) /var/lib/domogik/domogik_packages/plugin_diskfree
  - ls -l /var/lib/domogik/domogik_packages/plugin_diskfree
  - sudo /etc/init.d/domogik start
  - sleep 10
  - cat /var/log/domogik/manager.log
script:
  - python tests/010_tests.py
after_failure: 
  - ps -ef | grep dmg
  - cat /etc/default/domogik
  - cat /var/log/domogik/diskfree.log
  - cat /var/log/domogik/db_api.log
  - cat /var/log/domogik/dbmgr.log
  - cat /var/log/domogik/manager.log
  - cat /var/log/domogik/rest.log
  - cat /var/log/domogik/xplgw.log
  - cat /var/log/domogik/mq_broker.log
  - cat /var/log/xplhub/bandwidth.csv
  - cat /var/log/xplhub/client_list.txt
  - cat /var/log/xplhub/invalid_data.csv
  - cat /var/log/xplhub/xplhub.log
notifications:
  irc: "irc.freenode.net#domogik"

